local option = vim.o
option.cursorlineopt = "both"
option.tabstop = 8
option.softtabstop = 4
option.shiftwidth = 4
option.number = true
option.relativenumber = true
option.smartindent = true
option.smarttab = true
option.autoindent = true
option.expandtab = true
option.undofile = true
option.clipboard = "unnamedplus"
option.termguicolors = true
option.mousemoveevent = true
